<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'texto' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'texto' => array( 'integrated_edit_field4' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array(  ),
'above-grid' => array( 'view_back_list',
'view_close',
'view_edit',
'prev',
'next' ),
'below-grid' => array( 'integrated_edit_field4' ),
'grid' => array(  ) ),
'formXtTags' => array( 'top' => array(  ),
'below-grid' => array( 'texto_fieldblock' ) ),
'itemForms' => array( 'view_back_list' => 'above-grid',
'view_close' => 'above-grid',
'view_edit' => 'above-grid',
'prev' => 'above-grid',
'next' => 'above-grid',
'integrated_edit_field4' => 'below-grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'view_edit' => array( 'view_edit' ),
'prev' => array( 'prev' ),
'next' => array( 'next' ),
'edit_field' => array( 'integrated_edit_field4' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'view_edit',
'prev',
'next' ),
'align' => 'right' ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  color: red;
}
' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'rowspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => true ) ),
'items' => array( 'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'view_edit' => array( 'type' => 'view_edit' ),
'prev' => array( 'type' => 'prev' ),
'next' => array( 'type' => 'next' ),
'integrated_edit_field4' => array( 'field' => 'texto',
'type' => 'edit_field',
'mobileDisplay' => '',
'width' => '100%',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  color: red;
}
span {border:none;}
pre {
    background-color: #ffffff;
    border: 0px solid #ffffff;
    
}' ) ),
'dbProps' => array(  ),
'version' => 4,
'pageAlign' => 'left' );
		?>