<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'texto',
'tipo_de_documento',
'images_fs',
'documents_fs' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'texto' => array( 'integrated_edit_field3',
'edit_field_tooltip' ),
'tipo_de_documento' => array( 'edit_field' ),
'images_fs' => array( 'edit_field1',
'edit_field_label',
'edit_field_tooltip1' ),
'documents_fs' => array( 'edit_field2',
'edit_field_label1',
'edit_field_tooltip2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message',
'add_save1',
'add_back_list1',
'add_cancel1' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'edit_field',
'integrated_edit_field3',
'edit_field_tooltip',
'edit_field_label',
'edit_field1',
'edit_field_tooltip1',
'edit_field_label1',
'edit_field2',
'edit_field_tooltip2' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'add_save1' => 'above-grid',
'add_back_list1' => 'above-grid',
'add_cancel1' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'edit_field' => 'grid',
'integrated_edit_field3' => 'grid',
'edit_field_tooltip' => 'grid',
'edit_field_label' => 'grid',
'edit_field1' => 'grid',
'edit_field_tooltip1' => 'grid',
'edit_field_label1' => 'grid',
'edit_field2' => 'grid',
'edit_field_tooltip2' => 'grid' ),
'itemLocations' => array( 'edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_tooltip' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'edit_field1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'edit_field_tooltip1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'edit_field_label1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field2' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field_tooltip2' => array( 'location' => 'grid',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list',
'add_back_list1' ),
'add_cancel' => array( 'add_cancel',
'add_cancel1' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save',
'add_save1' ),
'edit_field' => array( 'integrated_edit_field3',
'edit_field',
'edit_field1',
'edit_field2' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'edit_field1',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'edit_field2',
'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'rowspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c1',
'items' => array( 'add_save1',
'add_back_list1',
'add_cancel1' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'rowspan' => 1 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field',
'integrated_edit_field3',
'edit_field_tooltip' ),
'field' => 'importe',
'align' => 'left',
'width' => '100%',
'height' => '100%',
'persistent' => true,
'useFullWidth' => true,
'orientation' => 'vertical' ),
'c1' => array( 'model' => 'c1',
'items' => array( 'edit_field_label',
'edit_field1',
'edit_field_tooltip1' ),
'field' => 'images_fs' ),
'c' => array( 'model' => 'c1',
'items' => array( 'edit_field_label1',
'edit_field2',
'edit_field_tooltip2' ),
'field' => 'documents_fs' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => true ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'registro',
'type' => 7 ) ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'integrated_edit_field3' => array( 'field' => 'texto',
'type' => 'edit_field',
'mobileDisplay' => '',
'width' => '90%',
'joined' => false,
'separated' => true,
'orientation' => 0 ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'texto',
'separated' => true ),
'edit_field' => array( 'field' => 'tipo_de_documento',
'type' => 'edit_field' ),
'add_save1' => array( 'type' => 'add_save' ),
'add_back_list1' => array( 'type' => 'add_back_list' ),
'add_cancel1' => array( 'type' => 'add_cancel' ),
'edit_field1' => array( 'field' => 'images_fs',
'type' => 'edit_field' ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'images_fs' ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'images_fs' ),
'edit_field2' => array( 'field' => 'documents_fs',
'type' => 'edit_field' ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'documents_fs' ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'documents_fs' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>