<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'texto',
'tipo_de_documento',
'images_fs',
'documents_fs' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'texto' => array( 'integrated_edit_texto',
'edit_field_label',
'edit_field_tooltip' ),
'tipo_de_documento' => array( 'edit_field',
'edit_field_label1',
'edit_field_tooltip1' ),
'images_fs' => array( 'edit_field1',
'edit_field_label2',
'edit_field_tooltip2' ),
'documents_fs' => array( 'edit_field2',
'edit_field_label3',
'edit_field_tooltip3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array(  ),
'above-grid' => array( 'edit_message',
'edit_save',
'edit_back_list',
'edit_close',
'prev',
'next',
'hamburger' ),
'below-grid' => array( 'edit_save1',
'edit_back_list1',
'edit_close1',
'prev1',
'next1' ),
'grid' => array( 'edit_field_label',
'integrated_edit_texto',
'edit_field_tooltip',
'edit_field_label1',
'edit_field',
'edit_field_tooltip1',
'edit_field_label2',
'edit_field1',
'edit_field_tooltip2',
'edit_field_label3',
'edit_field2',
'edit_field_tooltip3' ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'above-grid',
'edit_back_list' => 'above-grid',
'edit_close' => 'above-grid',
'prev' => 'above-grid',
'next' => 'above-grid',
'hamburger' => 'above-grid',
'edit_save1' => 'below-grid',
'edit_back_list1' => 'below-grid',
'edit_close1' => 'below-grid',
'prev1' => 'below-grid',
'next1' => 'below-grid',
'edit_field_label' => 'grid',
'integrated_edit_texto' => 'grid',
'edit_field_tooltip' => 'grid',
'edit_field_label1' => 'grid',
'edit_field' => 'grid',
'edit_field_tooltip1' => 'grid',
'edit_field_label2' => 'grid',
'edit_field1' => 'grid',
'edit_field_tooltip2' => 'grid',
'edit_field_label3' => 'grid',
'edit_field2' => 'grid',
'edit_field_tooltip3' => 'grid' ),
'itemLocations' => array( 'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_texto' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_tooltip' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_label1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'edit_field' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'edit_field_tooltip1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'edit_field_label2' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field_tooltip2' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field_label3' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'edit_field2' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'edit_field_tooltip3' => array( 'location' => 'grid',
'cellId' => 'c2' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save',
'edit_save1' ),
'edit_back_list' => array( 'edit_back_list',
'edit_back_list1' ),
'edit_close' => array( 'edit_close',
'edit_close1' ),
'edit_view' => array( 'edit_view' ),
'edit_field' => array( 'integrated_edit_texto',
'edit_field',
'edit_field1',
'edit_field2' ),
'next' => array( 'next',
'next1' ),
'prev' => array( 'prev',
'prev1' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2',
'edit_field_label3' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2',
'edit_field_tooltip3' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'edit_field',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label2',
'edit_field1',
'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field_label3',
'edit_field2',
'edit_field_tooltip3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'prev',
'next',
'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save1',
'edit_back_list1',
'edit_close1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'prev1',
'next1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c2',
'items' => array( 'edit_field_label',
'integrated_edit_texto',
'edit_field_tooltip' ),
'field' => 'importe',
'align' => 'left',
'orientation' => 'vertical',
'width' => '100%',
'height' => '100%',
'persistent' => true,
'useFullWidth' => true,
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'edit_field_label1',
'edit_field',
'edit_field_tooltip1' ),
'field' => 'tipo_de_documento' ),
'c' => array( 'model' => 'c1',
'items' => array( 'edit_field_label2',
'edit_field1',
'edit_field_tooltip2' ),
'field' => 'images_fs' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'edit_field_label3',
'edit_field2',
'edit_field_tooltip3' ),
'field' => 'documents_fs' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => true ) ),
'items' => array( 'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_texto' => array( 'field' => 'texto',
'type' => 'edit_field',
'updateOnEdit' => false,
'mobileDisplay' => '',
'joined' => false,
'separated' => true,
'orientation' => 1,
'width' => '100%',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  color: red;
}
' ),
'next' => array( 'type' => 'next' ),
'prev' => array( 'type' => 'prev' ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'texto',
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'texto',
'separated' => true ),
'edit_field' => array( 'field' => 'tipo_de_documento',
'type' => 'edit_field',
'updateOnEdit' => false ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'tipo_de_documento' ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'tipo_de_documento' ),
'edit_save1' => array( 'type' => 'edit_save' ),
'edit_back_list1' => array( 'type' => 'edit_back_list' ),
'edit_close1' => array( 'type' => 'edit_close' ),
'prev1' => array( 'type' => 'prev' ),
'next1' => array( 'type' => 'next' ),
'edit_field1' => array( 'field' => 'images_fs',
'type' => 'edit_field',
'updateOnEdit' => false ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'images_fs' ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'images_fs' ),
'edit_field2' => array( 'field' => 'documents_fs',
'type' => 'edit_field',
'updateOnEdit' => false ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'documents_fs' ),
'edit_field_tooltip3' => array( 'type' => 'edit_field_tooltip',
'field' => 'documents_fs' ) ),
'dbProps' => array(  ),
'version' => 4,
'pageWidth' => 'full',
'pageAlign' => 'left' );
		?>